3rd time lucky. Merged the two oaf patches together.
svn path=/trunk/; revision=5721

diff --git a/patches/oaf-glib-2.0.patch b/patches/oaf-glib-2.0.patch
--- a/patches/oaf-glib-2.0.patch
+++ b/patches/oaf-glib-2.0.patch
@@ -1,19 +1,384 @@
-diff -U2 -r oaf/oafd/ac-corba.c HEAD/oaf/oafd/ac-corba.c
---- oaf/oafd/ac-corba.c	Wed Aug  9 06:46:00 2000
-+++ HEAD/oaf/oafd/ac-corba.c	Thu Aug 31 01:22:32 2000
-@@ -122,5 +122,4 @@
+Index: acinclude.m4
+===================================================================
+RCS file: acinclude.m4
+diff -N acinclude.m4
+--- /dev/null	Tue May  5 16:32:27 1998
++++ acinclude.m4	Wed Aug 30 21:38:18 2000
+@@ -0,0 +1,335 @@
++# Macro to add for using GNU gettext.
++# Ulrich Drepper <drepper@cygnus.com>, 1995.
++#
++# Modified to never use included libintl. 
++# Owen Taylor <otaylor@redhat.com>, 12/15/1998
++#
++#
++# This file can be copied and used freely without restrictions.  It can
++# be used in projects which are not available under the GNU Public License
++# but which still want to provide support for the GNU gettext functionality.
++# Please note that the actual code is *not* freely available.
++
++# serial 5
++
++AC_DEFUN(AM_GNU_OAF_WITH_NLS,
++  [AC_MSG_CHECKING([whether NLS is requested])
++    dnl Default is enabled NLS
++    AC_ARG_ENABLE(nls,
++      [  --disable-nls           do not use Native Language Support],
++      USE_NLS=$enableval, USE_NLS=yes)
++    AC_MSG_RESULT($USE_NLS)
++    AC_SUBST(USE_NLS)
++
++    USE_INCLUDED_LIBINTL=no
++
++    dnl If we use NLS figure out what method
++    if test "$USE_NLS" = "yes"; then
++      AC_DEFINE(ENABLE_NLS)
++#      AC_MSG_CHECKING([whether included gettext is requested])
++#      AC_ARG_WITH(included-gettext,
++#        [  --with-included-gettext use the GNU gettext library included here],
++#        nls_cv_force_use_gnu_gettext=$withval,
++#        nls_cv_force_use_gnu_gettext=no)
++#      AC_MSG_RESULT($nls_cv_force_use_gnu_gettext)
++      nls_cv_force_use_gnu_gettext="no"
++
++      nls_cv_use_gnu_gettext="$nls_cv_force_use_gnu_gettext"
++      if test "$nls_cv_force_use_gnu_gettext" != "yes"; then
++        dnl User does not insist on using GNU NLS library.  Figure out what
++        dnl to use.  If gettext or catgets are available (in this order) we
++        dnl use this.  Else we have to fall back to GNU NLS library.
++	dnl catgets is only used if permitted by option --with-catgets.
++	nls_cv_header_intl=
++	nls_cv_header_libgt=
++	CATOBJEXT=NONE
++
++	AC_CHECK_HEADER(libintl.h,
++	  [AC_CACHE_CHECK([for gettext in libc], gt_cv_func_gettext_libc,
++	    [AC_TRY_LINK([#include <libintl.h>], [return (int) gettext ("")],
++	       gt_cv_func_gettext_libc=yes, gt_cv_func_gettext_libc=no)])
++
++	   if test "$gt_cv_func_gettext_libc" != "yes"; then
++	     AC_CHECK_LIB(intl, bindtextdomain,
++	       [AC_CACHE_CHECK([for gettext in libintl],
++		 gt_cv_func_gettext_libintl,
++		 [AC_CHECK_LIB(intl, gettext,
++		  gt_cv_func_gettext_libintl=yes,
++		  gt_cv_func_gettext_libintl=no)],
++		 gt_cv_func_gettext_libintl=no)])
++	   fi
++
++	   if test "$gt_cv_func_gettext_libc" = "yes" \
++	      || test "$gt_cv_func_gettext_libintl" = "yes"; then
++	      AC_DEFINE(HAVE_GETTEXT)
++	      AM_PATH_PROG_WITH_TEST(MSGFMT, msgfmt,
++		[test -z "`$ac_dir/$ac_word -h 2>&1 | grep 'dv '`"], no)dnl
++	      if test "$MSGFMT" != "no"; then
++		AC_CHECK_FUNCS(dcgettext)
++		AC_PATH_PROG(GMSGFMT, gmsgfmt, $MSGFMT)
++		AM_PATH_PROG_WITH_TEST(XGETTEXT, xgettext,
++		  [test -z "`$ac_dir/$ac_word -h 2>&1 | grep '(HELP)'`"], :)
++		AC_TRY_LINK(, [extern int _nl_msg_cat_cntr;
++			       return _nl_msg_cat_cntr],
++		  [CATOBJEXT=.gmo
++		   DATADIRNAME=share],
++		  [CATOBJEXT=.mo
++		   DATADIRNAME=lib])
++		INSTOBJEXT=.mo
++	      fi
++	    fi
++
++	    # Added by Martin Baulig 12/15/98 for libc5 systems
++	    if test "$gt_cv_func_gettext_libc" != "yes" \
++	       && test "$gt_cv_func_gettext_libintl" = "yes"; then
++	       INTLLIBS=-lintl
++	       LIBS=`echo $LIBS | sed -e 's/-lintl//'`
++	    fi
++	])
++
++        if test "$CATOBJEXT" = "NONE"; then
++	  AC_MSG_CHECKING([whether catgets can be used])
++	  AC_ARG_WITH(catgets,
++	    [  --with-catgets          use catgets functions if available],
++	    nls_cv_use_catgets=$withval, nls_cv_use_catgets=no)
++	  AC_MSG_RESULT($nls_cv_use_catgets)
++
++	  if test "$nls_cv_use_catgets" = "yes"; then
++	    dnl No gettext in C library.  Try catgets next.
++	    AC_CHECK_LIB(i, main)
++	    AC_CHECK_FUNC(catgets,
++	      [AC_DEFINE(HAVE_CATGETS)
++	       INTLOBJS="\$(CATOBJS)"
++	       AC_PATH_PROG(GENCAT, gencat, no)dnl
++#	       if test "$GENCAT" != "no"; then
++#		 AC_PATH_PROG(GMSGFMT, gmsgfmt, no)
++#		 if test "$GMSGFMT" = "no"; then
++#		   AM_PATH_PROG_WITH_TEST(GMSGFMT, msgfmt,
++#		    [test -z "`$ac_dir/$ac_word -h 2>&1 | grep 'dv '`"], no)
++#		 fi
++#		 AM_PATH_PROG_WITH_TEST(XGETTEXT, xgettext,
++#		   [test -z "`$ac_dir/$ac_word -h 2>&1 | grep '(HELP)'`"], :)
++#		 USE_INCLUDED_LIBINTL=yes
++#		 CATOBJEXT=.cat
++#		 INSTOBJEXT=.cat
++#		 DATADIRNAME=lib
++#		 INTLDEPS='$(top_builddir)/intl/libintl.a'
++#		 INTLLIBS=$INTLDEPS
++#		 LIBS=`echo $LIBS | sed -e 's/-lintl//'`
++#		 nls_cv_header_intl=intl/libintl.h
++#		 nls_cv_header_libgt=intl/libgettext.h
++#              fi
++            ])
++	  fi
++        fi
++
++        if test "$CATOBJEXT" = "NONE"; then
++	  dnl Neither gettext nor catgets in included in the C library.
++	  dnl Fall back on GNU gettext library.
++	  nls_cv_use_gnu_gettext=yes
++        fi
++      fi
++
++      if test "$nls_cv_use_gnu_gettext" != "yes"; then
++        AC_DEFINE(ENABLE_NLS)
++      else
++         # Unset this variable since we use the non-zero value as a flag.
++         CATOBJEXT=
++#        dnl Mark actions used to generate GNU NLS library.
++#        INTLOBJS="\$(GETTOBJS)"
++#        AM_PATH_PROG_WITH_TEST(MSGFMT, msgfmt,
++#	  [test -z "`$ac_dir/$ac_word -h 2>&1 | grep 'dv '`"], msgfmt)
++#        AC_PATH_PROG(GMSGFMT, gmsgfmt, $MSGFMT)
++#        AM_PATH_PROG_WITH_TEST(XGETTEXT, xgettext,
++#	  [test -z "`$ac_dir/$ac_word -h 2>&1 | grep '(HELP)'`"], :)
++#        AC_SUBST(MSGFMT)
++#	USE_INCLUDED_LIBINTL=yes
++#        CATOBJEXT=.gmo
++#        INSTOBJEXT=.mo
++#        DATADIRNAME=share
++#	INTLDEPS='$(top_builddir)/intl/libintl.a'
++#	INTLLIBS=$INTLDEPS
++#	LIBS=`echo $LIBS | sed -e 's/-lintl//'`
++#        nls_cv_header_intl=intl/libintl.h
++#        nls_cv_header_libgt=intl/libgettext.h
++      fi
++
++      dnl Test whether we really found GNU xgettext.
++      if test "$XGETTEXT" != ":"; then
++	dnl If it is no GNU xgettext we define it as : so that the
++	dnl Makefiles still can work.
++	if $XGETTEXT --omit-header /dev/null 2> /dev/null; then
++	  : ;
++	else
++	  AC_MSG_RESULT(
++	    [found xgettext program is not GNU xgettext; ignore it])
++	  XGETTEXT=":"
++	fi
++      fi
++
++      # We need to process the po/ directory.
++      POSUB=po
++    else
++      DATADIRNAME=share
++      nls_cv_header_intl=intl/libintl.h
++      nls_cv_header_libgt=intl/libgettext.h
++    fi
++    AC_LINK_FILES($nls_cv_header_libgt, $nls_cv_header_intl)
++    AC_OUTPUT_COMMANDS(
++     [case "$CONFIG_FILES" in *po/Makefile.in*)
++        sed -e "/POTFILES =/r po/POTFILES" po/Makefile.in > po/Makefile
++      esac])
++
++
++#    # If this is used in GNU gettext we have to set USE_NLS to `yes'
++#    # because some of the sources are only built for this goal.
++#    if test "$PACKAGE" = gettext; then
++#      USE_NLS=yes
++#      USE_INCLUDED_LIBINTL=yes
++#    fi
++
++    dnl These rules are solely for the distribution goal.  While doing this
++    dnl we only have to keep exactly one list of the available catalogs
++    dnl in configure.in.
++    for lang in $ALL_LINGUAS; do
++      GMOFILES="$GMOFILES $lang.gmo"
++      POFILES="$POFILES $lang.po"
++    done
++
++    dnl Make all variables we use known to autoconf.
++    AC_SUBST(USE_INCLUDED_LIBINTL)
++    AC_SUBST(CATALOGS)
++    AC_SUBST(CATOBJEXT)
++    AC_SUBST(DATADIRNAME)
++    AC_SUBST(GMOFILES)
++    AC_SUBST(INSTOBJEXT)
++    AC_SUBST(INTLDEPS)
++    AC_SUBST(INTLLIBS)
++    AC_SUBST(INTLOBJS)
++    AC_SUBST(POFILES)
++    AC_SUBST(POSUB)
++  ])
++
++AC_DEFUN(AM_GNU_OAF_GETTEXT,
++  [AC_REQUIRE([AC_PROG_MAKE_SET])dnl
++   AC_REQUIRE([AC_PROG_CC])dnl
++   AC_REQUIRE([AC_PROG_RANLIB])dnl
++   AC_REQUIRE([AC_ISC_POSIX])dnl
++   AC_REQUIRE([AC_HEADER_STDC])dnl
++   AC_REQUIRE([AC_C_CONST])dnl
++   AC_REQUIRE([AC_C_INLINE])dnl
++   AC_REQUIRE([AC_TYPE_OFF_T])dnl
++   AC_REQUIRE([AC_TYPE_SIZE_T])dnl
++   AC_REQUIRE([AC_FUNC_ALLOCA])dnl
++   AC_REQUIRE([AC_FUNC_MMAP])dnl
++
++   AC_CHECK_HEADERS([argz.h limits.h locale.h nl_types.h malloc.h string.h \
++unistd.h sys/param.h])
++   AC_CHECK_FUNCS([getcwd munmap putenv setenv setlocale strchr strcasecmp \
++strdup __argz_count __argz_stringify __argz_next])
++
++   if test "${ac_cv_func_stpcpy+set}" != "set"; then
++     AC_CHECK_FUNCS(stpcpy)
++   fi
++   if test "${ac_cv_func_stpcpy}" = "yes"; then
++     AC_DEFINE(HAVE_STPCPY)
++   fi
++
++   AM_LC_MESSAGES
++   AM_GNU_OAF_WITH_NLS
++
++   if test "x$CATOBJEXT" != "x"; then
++     if test "x$ALL_LINGUAS" = "x"; then
++       LINGUAS=
++     else
++       AC_MSG_CHECKING(for catalogs to be installed)
++       NEW_LINGUAS=
++       if test "x$LINGUAS" = "x"; then
++           LINGUAS=$ALL_LINGUAS
++       fi
++       for lang in $LINGUAS; do
++         case "$ALL_LINGUAS" in
++          *\ $lang\ *|$lang\ *|*\ $lang) NEW_LINGUAS="$NEW_LINGUAS $lang" ;;
++         esac
++       done
++       LINGUAS=$NEW_LINGUAS
++       AC_MSG_RESULT($LINGUAS)
++     fi
++
++     dnl Construct list of names of catalog files to be constructed.
++     if test -n "$LINGUAS"; then
++       for lang in $LINGUAS; do CATALOGS="$CATALOGS $lang$CATOBJEXT"; done
++     fi
++   fi
++
++   dnl The reference to <locale.h> in the installed <libintl.h> file
++   dnl must be resolved because we cannot expect the users of this
++   dnl to define HAVE_LOCALE_H.
++   if test $ac_cv_header_locale_h = yes; then
++     INCLUDE_LOCALE_H="#include <locale.h>"
++   else
++     INCLUDE_LOCALE_H="\
++/* The system does not provide the header <locale.h>.  Take care yourself.  */"
++   fi
++   AC_SUBST(INCLUDE_LOCALE_H)
++
++   dnl Determine which catalog format we have (if any is needed)
++   dnl For now we know about two different formats:
++   dnl   Linux libc-5 and the normal X/Open format
++   test -d intl || mkdir intl
++   if test "$CATOBJEXT" = ".cat"; then
++     AC_CHECK_HEADER(linux/version.h, msgformat=linux, msgformat=xopen)
++
++     dnl Transform the SED scripts while copying because some dumb SEDs
++     dnl cannot handle comments.
++     sed -e '/^#/d' $srcdir/intl/$msgformat-msg.sed > intl/po2msg.sed
++   fi
++   dnl po2tbl.sed is always needed.
++   sed -e '/^#.*[^\\]$/d' -e '/^#$/d' \
++     $srcdir/intl/po2tbl.sed.in > intl/po2tbl.sed
++
++   dnl In the intl/Makefile.in we have a special dependency which makes
++   dnl only sense for gettext.  We comment this out for non-gettext
++   dnl packages.
++   if test "$PACKAGE" = "gettext"; then
++     GT_NO="#NO#"
++     GT_YES=
++   else
++     GT_NO=
++     GT_YES="#YES#"
++   fi
++   AC_SUBST(GT_NO)
++   AC_SUBST(GT_YES)
++
++   dnl If the AC_CONFIG_AUX_DIR macro for autoconf is used we possibly
++   dnl find the mkinstalldirs script in another subdir but ($top_srcdir).
++   dnl Try to locate is.
++   MKINSTALLDIRS=
++   if test -n "$ac_aux_dir"; then
++     MKINSTALLDIRS="$ac_aux_dir/mkinstalldirs"
++   fi
++   if test -z "$MKINSTALLDIRS"; then
++     MKINSTALLDIRS="\$(top_srcdir)/mkinstalldirs"
++   fi
++   AC_SUBST(MKINSTALLDIRS)
++
++   dnl *** For now the libtool support in intl/Makefile is not for real.
++   l=
++   AC_SUBST(l)
++
++   dnl Generate list of files to be processed by xgettext which will
++   dnl be included in po/Makefile.
++   test -d po || mkdir po
++   if test "x$srcdir" != "x."; then
++     if test "x`echo $srcdir | sed 's@/.*@@'`" = "x"; then
++       posrcprefix="$srcdir/"
++     else
++       posrcprefix="../$srcdir/"
++     fi
++   else
++     posrcprefix="../"
++   fi
++   rm -f po/POTFILES
++   sed -e "/^#/d" -e "/^\$/d" -e "s,.*,	$posrcprefix& \\\\," -e "\$s/\(.*\) \\\\/\1/" \
++	< $srcdir/po/POTFILES.in > po/POTFILES
++  ])
+Index: configure.in
+===================================================================
+RCS file: /cvs/gnome/oaf/configure.in,v
+retrieving revision 1.33
+diff -u -p -r1.33 configure.in
+--- configure.in	2000/08/29 15:47:17	1.33
++++ configure.in	2000/08/31 01:38:18
+@@ -38,7 +38,7 @@ AM_GNU_OAF_GETTEXT
+ 
+ 
+ dnl Checks for libraries.
+-AM_PATH_GLIB(1.2.0,,
++AM_PATH_GLIB_2_0(1.3.0,,
+ AC_MSG_ERROR([
+ *** GLIB 1.2.0 or better is required. The latest version of GLIB
+ *** is always available from ftp://ftp.gtk.org/.]), gmodule)
+Index: oafd/ac-corba.c
+===================================================================
+RCS file: /cvs/gnome/oaf/oafd/ac-corba.c,v
+retrieving revision 1.30
+diff -u -p -r1.30 ac-corba.c
+--- oafd/ac-corba.c	2000/08/09 05:46:00	1.30
++++ oafd/ac-corba.c	2000/08/31 01:38:23
+@@ -121,13 +121,11 @@ child_od_update_active (ChildODInfo * ch
+ 		child->time_active_pulled = time (NULL);
  		child->active_servers =
  			g_hash_table_new (g_str_hash, g_str_equal);
 -		g_hash_table_freeze (child->active_servers);
  		for (i = 0; i < cache->_u.active_servers._length; i++)
  			g_hash_table_insert (child->active_servers,
-@@ -128,5 +127,4 @@
+ 					     cache->_u.
  					     active_servers._buffer[i],
  					     GINT_TO_POINTER (1));
 -		g_hash_table_thaw (child->active_servers);
  	} else
  		CORBA_free (cache);
-@@ -164,10 +162,8 @@
+ }
+@@ -163,12 +161,10 @@ child_od_update_list (ChildODInfo * chil
+ 
  		child->time_list_pulled = time (NULL);
  		child->by_iid = g_hash_table_new (g_str_hash, g_str_equal);
 -		g_hash_table_freeze (child->by_iid);
@@ -24,10 +389,16 @@ diff -U2 -r oaf/oafd/ac-corba.c HEAD/oaf/oafd/ac-corba.c
 -		g_hash_table_thaw (child->by_iid);
  	}
  
-diff -U2 -r oaf/oafd/od-load.c HEAD/oaf/oafd/od-load.c
---- oaf/oafd/od-load.c	Wed Aug  9 06:46:00 2000
-+++ HEAD/oaf/oafd/od-load.c	Thu Aug 31 01:22:49 2000
-@@ -321,10 +321,8 @@
+ 	CORBA_free (cache);
+Index: oafd/od-load.c
+===================================================================
+RCS file: /cvs/gnome/oaf/oafd/od-load.c,v
+retrieving revision 1.17
+diff -u -p -r1.17 od-load.c
+--- oafd/od-load.c	2000/08/09 05:46:00	1.17
++++ oafd/od-load.c	2000/08/31 01:38:24
+@@ -320,12 +320,10 @@ OAF_ServerInfo_load (char **dirs,
+ 
  	retval = CORBA_sequence_OAF_ServerInfo_allocbuf (n);
  
 -	g_hash_table_freeze (*by_iid);
@@ -38,3 +409,68 @@ diff -U2 -r oaf/oafd/od-load.c HEAD/oaf/oafd/od-load.c
 -	g_hash_table_thaw (*by_iid);
  
  	return retval;
+ }
+Index: po/Makefile.in.in
+===================================================================
+RCS file: /cvs/gnome/oaf/po/Makefile.in.in,v
+retrieving revision 1.3
+diff -u -p -r1.3 Makefile.in.in
+--- po/Makefile.in.in	2000/07/26 01:01:50	1.3
++++ po/Makefile.in.in	2000/08/31 01:38:25
+@@ -62,7 +62,7 @@ INSTOBJEXT = @INSTOBJEXT@
+ 	$(COMPILE) $<
+ 
+ .po.pox:
+-	$(MAKE) $(PACKAGE).pot
++	$(MAKE) $(srcdir)/$(PACKAGE).pot
+ 	$(MSGMERGE) $< $(srcdir)/$(PACKAGE).pot -o $*.pox
+ 
+ .po.mo:
+@@ -79,7 +79,7 @@ INSTOBJEXT = @INSTOBJEXT@
+ 
+ all: all-@USE_NLS@
+ 
+-all-yes: cat-id-tbl.c $(CATALOGS)
++all-yes: $(srcdir)/cat-id-tbl.c $(CATALOGS)
+ all-no:
+ 
+ $(srcdir)/$(PACKAGE).pot: $(POTFILES)
+@@ -90,8 +90,8 @@ $(srcdir)/$(PACKAGE).pot: $(POTFILES)
+ 	   || ( rm -f $(srcdir)/$(PACKAGE).pot \
+ 		&& mv $(PACKAGE).po $(srcdir)/$(PACKAGE).pot )
+ 
+-$(srcdir)/cat-id-tbl.c: stamp-cat-id; @:
+-$(srcdir)/stamp-cat-id: $(PACKAGE).pot
++$(srcdir)/cat-id-tbl.c: $(srcdir)/stamp-cat-id; @:
++$(srcdir)/stamp-cat-id: $(srcdir)/$(PACKAGE).pot
+ 	rm -f cat-id-tbl.tmp
+ 	sed -f ../intl/po2tbl.sed $(srcdir)/$(PACKAGE).pot \
+ 		| sed -e "s/@PACKAGE NAME@/$(PACKAGE)/" > cat-id-tbl.tmp
+@@ -180,7 +180,8 @@ uninstall:
+ 
+ check: all
+ 
+-cat-id-tbl.o: ../intl/libgettext.h
++cat-id-tbl.o: $(srcdir)/cat-id-tbl.c $(top_srcdir)/intl/libgettext.h
++	$(COMPILE) $(srcdir)/cat-id-tbl.c
+ 
+ dvi info tags TAGS ID:
+ 
+@@ -196,7 +197,7 @@ distclean: clean
+ maintainer-clean: distclean
+ 	@echo "This command is intended for maintainers to use;"
+ 	@echo "it deletes files that may require special tools to rebuild."
+-	rm -f $(GMOFILES)
++	rm -f $(GMOFILES) cat-id-tbl.c stamp-cat-id
+ 
+ distdir = ../$(PACKAGE)-$(VERSION)/$(subdir)
+ dist distdir: update-po $(DISTFILES)
+@@ -207,7 +208,7 @@ dist distdir: update-po $(DISTFILES)
+ 	done
+ 
+ update-po: Makefile
+-	$(MAKE) $(PACKAGE).pot
++	$(MAKE) $(srcdir)/$(PACKAGE).pot
+ 	PATH=`pwd`/../src:$$PATH; \
+ 	cd $(srcdir); \
+ 	catalogs='$(CATALOGS)'; \
